### ISSUE TITLE
Add missing pypi / conda package

### ISSUE THREAD

**Issue by MuellerSeb** [mcuntz/jams_python#10]
Hey Matthias,

what would you think about providing a pypi and/or conda package for jams?

Cheers,
Sebastian

**Comment by MuellerSeb** [comment]
Problem is, that `jams` is already on PyPI. What about `pyjams`? (Almost `pyjamas` :joy:)

**Comment by mcuntz** [comment]
Hey Sebastian,

pyjamas is already on PyPI: [pyjamas](https://pypi.org/project/Pyjamas/) ;-)

I have always seen JAMS as a development package rather than a module for PyPI. It is not really targeted on something specific. I use it as a repository for other standalone modules such as [partialwrap](https://github.com/mcuntz/partialwrap), [hesseflux](https://github.com/mcuntz/hesseflux), [pyeee](https://github.com/mcuntz/pyeee), and [ncvue](https://github.com/mcuntz/ncvue), and I update JAMS with developments in the other packages.

So I hesitate because making something available on PyPI should have at least some documentation and testing. Both are currently in the docstrings of the individual routines.

But if you think it is really worth it, I can rethink my hesitation ;-)

Cheers,
Matthias

**Comment by mcuntz** [comment]
Sorry Sebastian, I forgot to ping you with @MuellerSeb

**Comment by MuellerSeb** [comment]
I could help a bit with that (doc, testing). I think, that this repo should be used by people who rely on code referring to the "ufz" library. To ensure stuff is working as expected it would be nice to be able to have specific versions for the lib to be reproducible. All this could be achieved by having pypi releases/git tags. Even if the current state of this package is not optimal it would be better than having no reference on what version of an algorithm was used.

A documentation should be quite simple since the doc-strings are good.

Does a doc-test succeed? When there are tests in the doc-strings, one could think about just copying them into a unit-test file.

If you want, you can add me as maintainer/developer.

Cheers, Sebastian

**Comment by mcuntz** [comment]
Dear @MuellerSeb,

I cleaned the library so that I have no errors and hardly any warning when running the docstrings. I also updated the README.md. I then added a release tag; the number will follow the years.

I guess this is a compromise to publishing a PyPI and/or conda package. People can now install simply `pip install https://github.com/mcuntz/jams_python/archive/refs/tags/v21.0.zip`, for example.

I was hesitating about a PyPI/conda package because already I do not know who uses the package. Apart from you, there was never any demand for any addition, bug reports, etc. So I am assuming that the notion "ufz" library does not exists anymore.
JAMS is also a kaleidoscope of very different functions. I think PyPI/conda packackes should be a bit more targeted. There are of course very large collections such as [astropy](https://www.astropy.org) but they are maintained by a larger number of people.

As I told you, I am using JAMS as a development package for me. I then use routines in other, standalone modules such as [partialwrap](https://github.com/mcuntz/partialwrap), [hesseflux](https://github.com/mcuntz/hesseflux), [pyeee](https://github.com/mcuntz/pyeee), and [ncvue](https://github.com/mcuntz/ncvue). Only these routines have docstrings in numpydoc format. All others have the earlier docstring structure, which comes originally from IDL.

I agree that it is suboptimal to have some routines in several other packages (which are synchronised by hand). I could imagine a package such as `pyjams`, with only the routines that are used in other PyPI packages, which would then depend on `pyjams`. I would raise a warning in the routines in JAMS that they will be removed in two minor versions from then on.
This would also be a collection of very different things but there would be the reasoning that it feeds a few other projects, at least.

Kind regards,
Matthias

**Comment by MuellerSeb** [comment]
Hey Matthias,

thanks for this effort, I really appreciate it! All your arguments sound reasonable to me and I think having it this way should be fine and future-proof from now on. I get requests from time to time about the "ufz" library and how to install it, but most people are just using it without giving feedback.
Personally I want people to use "jams" from now on, since from my perspective there shouldn't be two libraries next to each other when only one is needed and you maybe also get more of the appreciation you deserve for all this coding work.

`pyjams` could then also start in a new repository to streamline your eco-system :wink: 

Thanks again for all your work and help,
Sebastian

**Comment by mcuntz** [comment]
Hey Sebastian @MuellerSeb 

I do not know if the ufz library is still updated. But if not then you should discourage people from using it; they should rather use jams. It gets bug fixes at least.

Jule, Stephan, Arndt, and I agreed to create a new repository pyjams with only routines that have numpydoc docstrings, are flake8 compatible, and have proper tests. They will be deprecated from jams (DeprecationWarning first). I would aim for >85% coverage.

I will start pretty soon but it will take a while to get up to speed (the tests, always the tests :-(. I will use your template again (rather the version that I adapted for myself). I did not use it in my last project [ncvue](https://github.com/mcuntz/ncvue) because readthedocs had problems with some special sphinx things. I use github.io there, which works pretty nicely as well, and you do not depend on yet another platform.

Do you know about conda-forge packages? I haven't done it yet but would be interested to add it there.

Kind regards,
Matthias

**Comment by MuellerSeb** [comment]
I can help with conda, once the package is on pypi. The package template needs some updates already. Maybe you could have a look at https://github.com/GeoStat-Framework/welltestpy. There I already use `pyproject.toml` (the new standard config file for python packages) and `setup.cfg` (config for setuptools) and dropped `setup.py`. Also the CI is updated to use GitHub-Actions to run tests on every platform. A really good packaging guide I read is given here: https://scikit-hep.org/developer/packaging

Some people still use the ufz lib, but it doesn't get any further updates, so I will discourage people to use it.

Kind regards,
Sebastian

**Comment by mcuntz** [comment]
Hey Sebastian @MuellerSeb 

we have `pyjams` now:
    https://github.com/mcuntz/pyjams
You might see that I borrowed a lot from `welltestpy`. This was fantastic. Thanks a lot. I hope I have it acknowledged enough in the docu.

I will migrate the JAMS library little by little to `pyjams` and raise DeprecationWarning in JAMS for the ported functions. I try to update/generalise the functions a bit when putting them in `pyjams` and I do proper tests with a large coverage. So it will take a while. It is mostly writing the tests that takes time.

`pyjams` is on PyPI. I put it also on conda-forge. This was pretty straight forward. However, I do not know how to update the conda-forge package. A `git tag -a "vX.X" -m "Message"` does not trigger it. This also does not trigger a Zenodo release. For the latter, I really have to do a 'manual' release on Github. So I thought that might be similar for conda-forge but the last 'manual' release of `pyjams` did not trigger anything on conda-forge.
Could you give me a hint, please?

Kind regards,
Matthias

**Comment by mcuntz** [comment]
Hey Sebastian @MuellerSeb

I changed the meta.yaml on pyjams-feedstock. pyjams was updated at conda-forge. But I do not know which of the actions triggered it, I might have tried a new action too quickly.
I will do "git tag", Github release, update meta.yml and leave two full days in between each step to find out.

**Comment by MuellerSeb** [comment]
Hey @mcuntz,

this is amazing! I really appreciate your work! I know the struggle with testing a lot of functions.. a coverage of 90+% is hard work!

Regarding conda-forge: As I see, you set up the package with its source from pypi. This means a bot of conda-forge, that scans pypi on a regular basis will see that the package needs to be updated if there is a new version on pypi. This is not immediately triggered by a git-tag or by pushing to pypi, but you need to wait for the bot to notice this change (should be less than a day from my experience). You can also update it by hand, but the bot does essentially this: creating a PR with all needed updates and you only need to approve and merge it. AFAIK there is also an option to auto-merge these simple update-PRs, but I always want to have a look at the changes, so I do the merges by hand in all my packages.

Kind regards,
Sebastian

**Comment by mcuntz** [comment]
Hey @MuellerSeb ,

I will discontinue JAMS and put all remaining routines as as subpackage of [pyjams](https://github.com/mcuntz/pyjams).

Kind regards,
Matthias
